### ISSUE TITLE
API not connect to server

### ISSUE THREAD

**Issue by Triumrus** [AntonYurchenko/energycronus#2]
login: api
password: vfnhbo8934ykfjhg

**Comment by Triumrus** [comment]
mysql

**Comment by AntonYurchenko** [comment]
![image](https://user-images.githubusercontent.com/25847429/34098286-d42e427e-e3ec-11e7-9fb2-aa1924b9b307.png)

**Comment by AntonYurchenko** [comment]
user with login API is not in database
